server:
  port: ${NODE_PORT:8086}

spring:
  datasource:
    url: ${POSTGRES_URL:jdbc:postgresql://localhost:5433/postgres}
    username: ${POSTGRES_USERNAME:user}
    password: ${POSTGRES_PASSWORD:user}
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        hbm2ddl:
          auto: update
  main:
    allow-bean-definition-overriding: true
  level:
    org.hibernate: DEBUG

salt: ${SALT:Pp12GSnZ5CwkrrkngnbiunfiubvnrinJIBVNRNBRUnJFGNIUgnriejngjndiugnUIPrgsdgjnsijnf}