server:
  port: ${NODE_PORT:8086}
spring:
  datasource:
    url: ${POSTGRES_URL:jdbc:postgresql://localhost:5433/postgres}
    username: ${POSTGRES_USERNAME:user}
    password: ${POSTGRES_PASSWORD:user}
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        hbm2ddl:
          auto: update
salt: ${SALT:Pp12GSnZ5CwkrrkngnbiunfiubvnrinJIBVNRNBRUnJFGNIUgnriejngjndiugnUIPrgsdgjnsijnf}