server :
  port : 8086
spring:
  datasource:
    url : jdbc:postgresql://localhost:5432/postgres
    username : user
    password : user

  jpa :
    properties :
      hibernate:
        hbm2ddl:
          auto : update